# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(max_length=15),
        ),
    ]
