# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20171115_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
